# Generated by Django 5.2.9 on 2025-12-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Arduino, C++, Python, React', max_length=200)),
                ('github_link', models.URLField()),
                ('live_link', models.URLField(blank=True, help_text='Optional link to live demo or deployed project', null=True)),
                ('image_url', models.URLField(help_text='Link to an image representing the project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
