# Generated by Django 5.2.9 on 2025-12-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactmesage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMesage',
            new_name='ContactMessage',
        ),
    ]
