upstream api_prod {
    server web-prod:8000;
}

upstream api_test {
    server web-test:8000;
}

# 1. PROD API (HTTP - We will add HTTPS later)
server {
    listen 80;
    server_name api.nic-ball.co.uk;

    # Allow Certbot to verify domain
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://api_prod;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
    
    location /static/ { alias /home/app/web/staticfiles/; }
    location /media/ { alias /home/app/web/mediafiles/; }
}

# 2. TEST API
server {
    listen 80;
    server_name test-api.nic-ball.co.uk;

    # Allow Certbot to verify domain
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://api_test;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
    location /static/ { alias /home/app/web/staticfiles/; }
}

# 3. FRONTEND
server {
    listen 80;
    server_name portfolio.nic-ball.co.uk nic-ball.co.uk;

    # Allow Certbot to verify domain
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    root /var/www/portfolio;
    index index.html;
    location / { try_files $uri $uri/ /index.html; }
}
